package Enums;
/**
 * Types of nationality for a user
 */
public enum Nationality {
    AFGHAN, ARMENIAN, AUSTRALIAN,BENGALI,BELIZEAN,BRAZILIAN,BURMESE,CAMBODIAN
    ,CANADIAN,CENTRAL_AFRICAN,CHILEAN,CHINESE,COLOMBIAN,COSTA_RICAN,CUBAN
    ,EGYPTIAN,ETHIOPIAN,FIJIAN,FINNISH,FRENCH,GERMAN,GIBRALTAR,HUNGARIAN
    ,INDIAN,INDONESIAN,IRISH,ITALIAN,JAPANESE,KOREAN,MALAYSIAN,MEXICAN,MONGOLIAN
    ,PAKISTANI,FILIPINO,RUSSIAN,SIERRA_LEONEAN, SINGAPOREAN,SWISS,THAI,TURKISH
    ,UK_BRITISH, US_AMERICAN,VIETNAMESE,ZIMBABWEAN;

}
